---
- name: "Download Elasticsearch's rpm"
  become: true
  get_url:
    url: https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-{{ elasticsearch_version }}-x86_64.rpm
    dest: /home/rattle/elasticsearch-{{ elasticsearch_version }}-x86_64.rpm
  register: download_elastic
  until: download_elastic is succeeded
  when: elastic_install_type == 'remote'
